name: maven.java-jar.build
run-name: Running maven.java-jar.build
on:
  push:         # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
    paths:      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - 'maven/java-jar/**'
jobs:
  build:
    name: build-job
    runs-on: ubuntu-22.04
    steps:
      - id: step-1
        run: |
          echo "Ran step-1"
          
